data-agent:
  vector-store:
    type: milvus
    milvus-uri: ${MILVUS_URI:http://127.0.0.1:19530}
    milvus-token: ${MILVUS_TOKEN:}
    milvus-database: ${MILVUS_DATABASE:default}
    milvus-collection: ${MILVUS_COLLECTION:vector_store}
    embedding-dimension: ${MILVUS_DIMENSION:1024}
